/**
 * Onboard Command
 *
 * Hybrid onboarding: terminal prompts for API keys, then agent-guided infrastructure setup.
 */

import { mkdir, writeFile, copyFile } from 'fs/promises';
import { existsSync } from 'fs';
import { join } from 'path';
import { homedir } from 'os';
import * as readline from 'readline/promises';
import { stdin as input, stdout as output } from 'process';
import { Server } from '@system2/gateway';
import open from 'open';

const SYSTEM2_DIR = join(homedir(), '.system2');
const ENV_FILE = join(SYSTEM2_DIR, '.env');
const DB_FILE = join(SYSTEM2_DIR, 'app.db');

interface OnboardConfig {
  primaryProvider: 'anthropic' | 'openai' | 'google';
  primaryApiKey: string;
  secondaryProvider?: 'anthropic' | 'openai' | 'google';
  secondaryApiKey?: string;
}

export async function onboard(): Promise<void> {
  console.log('');
  console.log('╔══════════════════════════════════════╗');
  console.log('║   Welcome to System2 Onboarding      ║');
  console.log('╚══════════════════════════════════════╝');
  console.log('');

  // Phase 1: Terminal Prompts (Credentials Only)
  console.log('Phase 1: Configure LLM Providers\n');

  const rl = readline.createInterface({ input, output });

  try {
    // Primary provider
    console.log('Primary LLM Provider (required):');
    console.log('  1. Anthropic Claude');
    console.log('  2. OpenAI');
    console.log('  3. Google Gemini');
    const providerChoice = await rl.question('Select provider (1-3): ');

    const providerMap: Record<string, 'anthropic' | 'openai' | 'google'> = {
      '1': 'anthropic',
      '2': 'openai',
      '3': 'google',
    };

    const primaryProvider = providerMap[providerChoice.trim()];
    if (!primaryProvider) {
      console.error('Invalid provider choice');
      process.exit(1);
    }

    const primaryApiKey = await rl.question(`Enter ${primaryProvider} API key: `);
    if (!primaryApiKey.trim()) {
      console.error('API key is required');
      process.exit(1);
    }

    // Secondary provider (optional)
    console.log('\nSecondary LLM Provider (optional fallback):');
    console.log('  1. Anthropic Claude');
    console.log('  2. OpenAI');
    console.log('  3. Google Gemini');
    console.log('  4. None');
    const secondaryChoice = await rl.question('Select provider (1-4, default: 4): ') || '4';

    let secondaryProvider: 'anthropic' | 'openai' | 'google' | undefined;
    let secondaryApiKey: string | undefined;

    if (secondaryChoice !== '4') {
      secondaryProvider = providerMap[secondaryChoice.trim()];
      if (secondaryProvider) {
        secondaryApiKey = await rl.question(`Enter ${secondaryProvider} API key: `);
      }
    }

    rl.close();

    const config: OnboardConfig = {
      primaryProvider,
      primaryApiKey: primaryApiKey.trim(),
      secondaryProvider,
      secondaryApiKey: secondaryApiKey?.trim(),
    };

    // Phase 2: Bootstrap
    console.log('\nPhase 2: Bootstrap System2');
    await bootstrap(config);

    // Phase 3: Launch
    console.log('\nPhase 3: Launching System2');
    await launch(config);

  } catch (error) {
    console.error('Onboarding failed:', error);
    process.exit(1);
  }
}

async function bootstrap(config: OnboardConfig): Promise<void> {
  // Create ~/.system2/ directory structure
  if (!existsSync(SYSTEM2_DIR)) {
    await mkdir(SYSTEM2_DIR, { recursive: true });
    console.log(`✓ Created ${SYSTEM2_DIR}`);
  }

  // Create subdirectories
  await mkdir(join(SYSTEM2_DIR, 'agents'), { recursive: true });
  await mkdir(join(SYSTEM2_DIR, 'projects'), { recursive: true });
  await mkdir(join(SYSTEM2_DIR, 'artifacts'), { recursive: true });
  console.log('✓ Created directory structure');

  // Write .env file
  let envContent = `# System2 Configuration
# Generated by onboard command

# Primary LLM Provider
PRIMARY_LLM_PROVIDER=${config.primaryProvider}
${getApiKeyEnvVar(config.primaryProvider)}=${config.primaryApiKey}
`;

  if (config.secondaryProvider && config.secondaryApiKey) {
    envContent += `
# Secondary LLM Provider (Fallback)
SECONDARY_LLM_PROVIDER=${config.secondaryProvider}
${getApiKeyEnvVar(config.secondaryProvider)}=${config.secondaryApiKey}
`;
  }

  await writeFile(ENV_FILE, envContent);
  console.log('✓ Saved API keys to .env');

  // Initialize app.db (will be created by DatabaseClient with schema)
  console.log('✓ Initialized app.db');
}

async function launch(config: OnboardConfig): Promise<void> {
  // Determine LLM model based on provider
  const modelMap: Record<string, string> = {
    anthropic: 'claude-sonnet-4-5',
    openai: 'gpt-4o',
    google: 'gemini-2.5-pro',
  };

  const model = modelMap[config.primaryProvider];

  console.log(`Starting gateway server...`);
  console.log(`  Provider: ${config.primaryProvider}`);
  console.log(`  Model: ${model}`);

  // Start server
  const server = new Server({
    port: 3000,
    dbPath: DB_FILE,
    llmProvider: config.primaryProvider,
    llmModel: model,
    // UI dist path will be set once UI package is built
  });

  await server.start();

  // Open browser
  console.log('\nOpening browser...');
  await open('http://localhost:3000');

  console.log('');
  console.log('✅ System2 is ready!');
  console.log('');
  console.log('The Guide agent is now active and ready to help you:');
  console.log('  1. Detect your system and installed tools');
  console.log('  2. Configure your data stack (databases, orchestration)');
  console.log('  3. Set up your pipelines repository');
  console.log('');
  console.log('Press Ctrl+C to stop the server');
  console.log('');

  // Keep server running
  await new Promise(() => {});
}

function getApiKeyEnvVar(provider: string): string {
  const map: Record<string, string> = {
    anthropic: 'ANTHROPIC_API_KEY',
    openai: 'OPENAI_API_KEY',
    google: 'GEMINI_API_KEY',
  };
  return map[provider];
}
